import { PrismaClient } from '@prisma/client'   // PrismaClient is generated by Prisma
const prisma = new PrismaClient()              // Create a new PrismaClient instance    

export const createInstitute = async (facultyID,name,gender,designation,date_of_joining,aicte_id,state) => {
    
    const institute = await prisma.institute.create({
        data: {
            facultyID: facultyID,
            name: name,
            gender: gender,
            designation: designation,
            date_of_joining: date_of_joining,
            aicte_id: aicte_id,
            state: state 
        }
    });
    return institute;
    
} 

export const getAllinstitute = async () => {
    const institute = await prisma.institute.findMany({
        facultyID: facultyID
    })
    return institute;
}